# Generated by Django 5.0.2 on 2024-03-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_recipe_author_recipe_created_on_recipe_updated_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='course',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='year_level',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.CharField(default='2', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
